from app.models.document_schemas import (
    Form16Data,
    Form16AData,
    Form26ASData,
    AISData,
    TISData,
    SalarySlipData,
    PensionStatementData,
    GratuityStatementData,
    EPFStatementData,
    PPFPassbookData,
    NPSStatementData,
    ELSSStatementData,
    ULIPStatementData,
    BankStatementData,
    FDInterestCertificateData,
    SavingsInterestCertificateData,
    BrokerStatementData,
    MutualFundCASData,
    DematStatementData,
    DividendStatementData,
    CapitalGainsStatementData,
    HomeLoanInterestCertificateData,
    RentalIncomeStatementData,
    RentReceiptsData,
    LifeInsurancePremiumData,
    MedicalInsurance80DData,
    DonationReceipt80GData,
    EducationLoanCertificateData,
    TuitionFeeReceiptData,
    HRADeclarationData,
    RSUStatementData,
    ESOPStatementData,
    CryptoTransactionStatementData,
    ForeignAssetStatementData,
    GSTReturnData,
    ProfitLossStatementData,
    BalanceSheetData,
    BusinessIncomeStatementData,
    ProfessionalIncomeStatementData,
    PartnershipIncomeStatementData,
    AgriculturalIncomeStatementData,
    FreelancerInvoiceData,
    SpeculativeIncomeStatementData,
    LotteryWinningsStatementData,
    ForeignIncomeStatementData,
)

DOCUMENT_SCHEMAS = {
    "Form16": Form16Data,
    "Form16A": Form16AData,
    "Form26AS": Form26ASData,
    "AIS": AISData,
    "TIS": TISData,
    "Salary Slip": SalarySlipData,
    "Pension Statement": PensionStatementData,
    "Gratuity Statement": GratuityStatementData,
    "EPF Statement": EPFStatementData,
    "PPF Passbook": PPFPassbookData,
    "NPS Statement": NPSStatementData,
    "ELSS Statement": ELSSStatementData,
    "ULIP Statement": ULIPStatementData,
    "Bank Statement": BankStatementData,
    "FD Interest Certificate": FDInterestCertificateData,
    "Savings Interest Certificate": SavingsInterestCertificateData,
    "Broker Statement": BrokerStatementData,
    "Mutual Fund CAS": MutualFundCASData,
    "Demat Statement": DematStatementData,
    "Dividend Statement": DividendStatementData,
    "Capital Gains Statement": CapitalGainsStatementData,
    "Home Loan Interest Certificate": HomeLoanInterestCertificateData,
    "Rental Income Statement": RentalIncomeStatementData,
    "Rent Receipts": RentReceiptsData,
    "Life Insurance Premium": LifeInsurancePremiumData,
    "Medical Insurance (80D)": MedicalInsurance80DData,
    "Donation Receipt (80G)": DonationReceipt80GData,
    "Education Loan Certificate": EducationLoanCertificateData,
    "Tuition Fee Receipt": TuitionFeeReceiptData,
    "HRA Declaration": HRADeclarationData,
    "RSU Statement": RSUStatementData,
    "ESOP Statement": ESOPStatementData,
    "Crypto Transaction Statement": CryptoTransactionStatementData,
    "Foreign Asset Statement": ForeignAssetStatementData,
    "GST Return": GSTReturnData,
    "Profit & Loss Statement": ProfitLossStatementData,
    "Balance Sheet": BalanceSheetData,
    "Business Income Statement": BusinessIncomeStatementData,
    "Professional Income Statement": ProfessionalIncomeStatementData,
    "Partnership Income Statement": PartnershipIncomeStatementData,
    "Agricultural Income Statement": AgriculturalIncomeStatementData,
    "Freelancer Invoice": FreelancerInvoiceData,
    "Speculative Income Statement": SpeculativeIncomeStatementData,
    "Lottery Winnings Statement": LotteryWinningsStatementData,
    "Foreign Income Statement": ForeignIncomeStatementData,
}
